### ISSUE TITLE
iOS tracking issue

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/badgemagic-app#642]
Let's track the progress here till the app is in usable state

- [x] shifting iOS app here #604 
- [x] iOS framework build failed #607 
- [x] deployment of iOS is not working #611  
- [x] Make iOS independent from framework generation #639 
- [ ] Use shared platform to implement transfer #648
